//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_HomeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.books = new HashSet<book>();
        }
    
        public int language_id { get; set; }
        public string language_name { get; set; }
        public int countrie_country_id { get; set; }
    
        public virtual ICollection<book> books { get; set; }
        public virtual countrie countrie { get; set; }
    }
}
